apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  label:
    app: multi-pod
    kind: frontend

spec:
  containers:
    - name: nginx:alpine
      image: nginx:alpine

    - name: redis
      image: redis
      
    - name: memcached
      image: memcached
 